---
title: "Pilot heatmap"
author: 'Dave Braun'
date: '7-27-2021'
output: 
  html_document:
    code_folding: hide
    theme: flatly
    df_print: paged
---

```{r include = FALSE}
library(tidyverse)
library(plotly)

d <- read.csv('../data/compare_lines.csv')
head(d)

keep <- c('participant', 'line_orientation', 'SeqResponse.keys', 'SeqResponse.rt', 'ResponseSimul.keys', 'ResponseSimul.rt', 'left_width', 'right_width', 'first_line_label', 'second_line_label')

d <- d[,keep]

deidentify <- data.frame(participant = names(summary(factor(d$participant))), id = sample(c('a', 'b', 'c'), size = 3, replace = FALSE))

d <- d %>% 
  inner_join(deidentify, by = 'participant') %>% 
  select(-participant)

N <- d %>% 
  group_by(id) %>% 
  summarize(n()) %>% 
  nrow()

## tricky reshaping
colnames(d)[4:5] <- c('SimulResponse.keys', 'SimulResponse.rt')
d$row_id <- 1:(nrow(d))
d <- d %>% 
  gather(var, value, SeqResponse.keys, SeqResponse.rt, SimulResponse.keys, SimulResponse.rt) %>% 
  separate(var, c('block', 'response_type')) %>% 
  spread(response_type, value) %>% 
  filter(!is.na(rt))

## code accuracy
d$accuracy <- ifelse(d$left_width < d$right_width & d$keys == 'right', 1, 
                     ifelse(d$right_width < d$left_width & d$keys == 'left', 1,
                            ifelse(d$right_width == d$left_width & d$keys == 'down', 1, 0)))

## round widths
d$left_width <- round(d$left_width, 2)
d$right_width <- round(d$right_width, 2)

## keep widths in same order
d$small_width <- ifelse(d$left_width > d$right_width, d$right_width, d$left_width)
d$large_width <- ifelse(d$left_width > d$right_width, d$left_width, d$right_width)

p1 <- d %>% 
  unite('combinations', c('small_width', 'large_width'), sep = '-') %>% 
  group_by(id, combinations, block) %>% 
  summarize(accuracy = mean(accuracy)) %>% 
  group_by(combinations, block) %>% 
  summarize(accuracy = mean(accuracy)) %>% 
  separate(combinations, c('small_width', 'large_width'), sep = '-') %>% 
  mutate(text = paste0('Small width: ', small_width, '\nLarge Width: ', large_width, '\nAccuracy: ', round(accuracy,2))) %>% 
  ggplot(aes(x = small_width, y = large_width, fill = accuracy, text = text)) + 
  geom_tile() +
  facet_wrap(~block) +
  labs(
    x = 'Line 1',
    y = 'Line 2',
    fill = 'Accuracy'
  ) + 
  theme_bw() +
  theme(strip.background = element_rect(fill = NA, color = 'black'))




```
```{r}
ggplotly(p1, tooltip = 'text')
```

